/**
 * Band name generator — pure functions ported verbatim from the `game-music`
 * frontend `BandNameGenerator` (read-only reference). Supports language,
 * article and genre options. No side effects beyond `Math.random()`.
 */

/** Supported name languages. */
export type NameLanguage = "pt" | "en" | "es";

/** Supported genre hints. */
export type NameGenre = "rock" | "metal" | "electronic" | "punk";

/** Options controlling name generation. */
export interface GenerateNameOptions {
  language?: NameLanguage;
  includeArticle?: boolean;
  genre?: NameGenre;
}

interface WordBank {
  adjectives: string[];
  nouns: string[];
  verbs: string[];
  places: string[];
  concepts: string[];
  articles: string[];
  connectors: string[];
  prefixes: string[];
}

const WORDS: Record<NameLanguage, WordBank> = {
  pt: {
    adjectives: [
      "Solitário",
      "Eterno",
      "Veloz",
      "Sagrado",
      "Escuro",
      "Lunar",
      "Elétrico",
      "Caótico",
      "Silencioso",
      "Feroz",
      "Dourado",
      "Ultra",
      "Cósmico",
      "Nuclear",
      "Psicodélico",
      "Sombrio",
      "Radioativo",
      "Cristalino",
      "Arcano",
      "Mecânico",
      "Digital",
      "Primitivo",
      "Celestial",
      "Subterrâneo",
      "Desértico",
      "Oceânico",
      "Florestal",
      "Metálico",
      "Vulcânico",
      "Glacial",
      "Quântico",
      "Atômico",
      "Místico",
      "Congelado",
      "Incandescente",
      "Noturno",
      "Diurno",
      "Etéreo",
      "Ancestral",
      "Futurista",
      "Retro",
      "Neon",
      "Gótico",
      "Punk",
      "Industrial",
      "Distópico",
      "Utópico",
      "Mítico",
      "Lendário",
      "Perdido",
      "Esquecido",
      "Renascido",
      "Decadente",
      "Emergente",
      "Implacável",
      "Inquebrável",
      "Invisível",
      "Inefável",
    ],
    nouns: [
      "Trovão",
      "Lobo",
      "Rei",
      "Abismo",
      "Segredo",
      "Vértice",
      "Eco",
      "Vulcão",
      "Oceano",
      "Coração",
      "Fantasma",
      "Templo",
      "Dragão",
      "Fênix",
      "Colosso",
      "Titã",
      "Gigante",
      "Anjo",
      "Demônio",
      "Profeta",
      "Xamã",
      "Necromante",
      "Alquimista",
      "Andarilho",
      "Nômade",
      "Peregrino",
      "Cavaleiro",
      "Samurai",
      "Viking",
      "Gladiador",
      "Mago",
      "Bruxo",
      "Feiticeiro",
      "Oráculo",
      "Sábio",
      "Iluminado",
      "Mártir",
      "Herói",
      "Vilão",
      "Mercenário",
      "Corsário",
      "Pirata",
      "Astrólogo",
      "Astrônomo",
      "Cosmonauta",
      "Viajante",
      "Explorador",
      "Pioneiro",
      "Desbravador",
      "Névoa",
      "Tempestade",
      "Furacão",
      "Tsunami",
      "Terremoto",
      "Avalanche",
      "Erupção",
      "Ciclone",
      "Tornado",
      "Vendaval",
      "Monólito",
      "Obelisco",
      "Pirâmide",
      "Zigurate",
      "Cidadela",
      "Fortaleza",
      "Bastilha",
      "Castelo",
      "Palácio",
      "Mansão",
      "Catedral",
      "Mosteiro",
      "Santuário",
      "Sacrário",
      "Altar",
      "Panteão",
      "Olimpo",
      "Valhalla",
      "Nirvana",
      "Éden",
      "Inferno",
      "Purgatório",
      "Limbo",
      "Vazio",
      "Vácuo",
      "Vórtice",
      "Singularidade",
      "Buraco Negro",
      "Galáxia",
      "Constelação",
      "Nebulosa",
      "Supernova",
      "Cometa",
      "Asteroide",
      "Meteoro",
      "Planeta",
      "Satélite",
      "Lua",
      "Sol",
      "Estrela",
      "Eclipse",
      "Aurora",
      "Crepúsculo",
      "Alba",
      "Ocaso",
      "Meia-Noite",
      "Madrugada",
    ],
    verbs: [
      "Rugindo",
      "Gritando",
      "Sussurrando",
      "Cantando",
      "Dançando",
      "Voando",
      "Caindo",
      "Ascendendo",
      "Descendendo",
      "Queimando",
      "Congelando",
      "Dissolvendo",
      "Criando",
      "Destruindo",
      "Transformando",
      "Evoluindo",
      "Devorando",
      "Consumindo",
      "Purificando",
      "Corrompendo",
      "Iluminando",
      "Escurecendo",
      "Curando",
      "Envenenando",
      "Amaldiçoando",
      "Abençoando",
      "Profetizando",
      "Adivinhando",
      "Lembrando",
      "Esquecendo",
      "Sonhando",
      "Acordando",
      "Dormindo",
      "Vivendo",
      "Morrendo",
      "Renascendo",
      "Perecendo",
    ],
    places: [
      "Cemitério",
      "Deserto",
      "Floresta",
      "Montanha",
      "Caverna",
      "Gruta",
      "Abismo",
      "Penhasco",
      "Ilha",
      "Continente",
      "Planície",
      "Vale",
      "Cânion",
      "Ravina",
      "Garganta",
      "Estreito",
      "Oceano",
      "Rio",
      "Lago",
      "Lagoa",
      "Cachoeira",
      "Geleira",
      "Vulcão",
      "Cratera",
      "Metrópole",
      "Cidade",
      "Vila",
      "Aldeia",
      "Favela",
      "Subúrbio",
      "Centro",
      "Periferia",
      "Estação",
      "Porto",
      "Aeroporto",
      "Terminal",
      "Garagem",
      "Armazém",
      "Depósito",
      "Laboratório",
      "Observatório",
      "Biblioteca",
      "Arquivo",
      "Museu",
      "Galeria",
      "Teatro",
      "Cinema",
      "Arena",
      "Coliseu",
      "Estádio",
      "Academia",
      "Santuário",
      "Altar",
      "Tabernáculo",
      "Mosteiro",
      "Convento",
      "Ermida",
      "Capela",
      "Igreja",
      "Catedral",
      "Mesquita",
      "Sinagoga",
      "Templo",
      "Pagode",
      "Zigurate",
      "Pirâmide",
      "Torre",
      "Farol",
      "Bunker",
      "Silo",
      "Mina",
      "Túnel",
      "Catacumba",
      "Cripta",
      "Mausoléu",
      "Sepulcro",
      "Nave",
      "Foguete",
      "Ônibus Espacial",
      "Estação Espacial",
      "Planeta",
      "Lua",
      "Asteroide",
      "Cometa",
      "Nebulosa",
      "Galáxia",
      "Universo",
      "Multiverso",
      "Realidade",
      "Dimensão",
    ],
    concepts: [
      "Liberdade",
      "Destino",
      "Sorte",
      "Azar",
      "Amor",
      "Ódio",
      "Paz",
      "Guerra",
      "Caos",
      "Ordem",
      "Tempo",
      "Espaço",
      "Matéria",
      "Energia",
      "Consciência",
      "Inconsciência",
      "Memória",
      "Esquecimento",
      "Verdade",
      "Mentira",
      "Realidade",
      "Ilusão",
      "Sonho",
      "Pesadelo",
      "Vida",
      "Morte",
      "Ressurreição",
      "Reencarnação",
      "Transcendência",
      "Iluminação",
      "Salvação",
      "Condenação",
      "Paraíso",
      "Inferno",
      "Purgatório",
      "Nirvana",
      "Êxtase",
      "Agonia",
      "Prazer",
      "Dor",
      "Alegria",
      "Tristeza",
      "Raiva",
      "Calma",
      "Loucura",
      "Sanidade",
      "Gênio",
      "Insanidade",
      "Beleza",
      "Horror",
      "Sublime",
      "Terrível",
      "Divino",
      "Profano",
      "Sagrado",
      "Amaldiçoado",
      "Abençoado",
      "Puro",
      "Impuro",
      "Inocente",
      "Culpado",
      "Vingança",
      "Perdão",
      "Redenção",
      "Queda",
      "Ascensão",
    ],
    articles: ["Os", "As", "O", "A", "Um", "Uma", "Uns", "Umas"],
    connectors: [
      "do",
      "da",
      "de",
      "dos",
      "das",
      "no",
      "na",
      "nos",
      "nas",
      "pelo",
      "pela",
    ],
    prefixes: [
      "Anti",
      "Arque",
      "Auto",
      "Bi",
      "Co",
      "Contra",
      "Des",
      "Ex",
      "Hiper",
      "Infra",
      "Inter",
      "Intra",
      "Macro",
      "Micro",
      "Mono",
      "Multi",
      "Neo",
      "Pan",
      "Pós",
      "Pré",
      "Pró",
      "Re",
      "Retro",
      "Semi",
      "Sobre",
      "Sub",
      "Super",
      "Supra",
      "Tele",
      "Trans",
      "Tri",
      "Ultra",
      "Vice",
      "Cyber",
      "Tecno",
      "Neuro",
      "Bio",
      "Eco",
      "Geo",
      "Aero",
      "Hidro",
      "Piro",
      "Cripto",
      "Digi",
      "Meta",
      "Nano",
      "Omni",
      "Paleo",
      "Proto",
      "Psico",
      "Quantum",
      "Rádio",
      "Termo",
      "Xeno",
    ],
  },
  en: {
    adjectives: [
      "Solitary",
      "Eternal",
      "Swift",
      "Sacred",
      "Dark",
      "Lunar",
      "Electric",
      "Chaotic",
      "Silent",
      "Fierce",
      "Golden",
      "Ultra",
      "Cosmic",
      "Nuclear",
      "Psychedelic",
      "Gloomy",
      "Radioactive",
      "Crystalline",
      "Arcane",
      "Mechanical",
      "Digital",
      "Primitive",
      "Celestial",
      "Underground",
      "Desert",
      "Oceanic",
      "Forest",
      "Metallic",
      "Volcanic",
      "Glacial",
      "Quantum",
      "Atomic",
      "Mystic",
      "Frozen",
      "Incandescent",
      "Nocturnal",
      "Diurnal",
      "Ethereal",
      "Ancestral",
      "Futuristic",
      "Retro",
      "Neon",
      "Gothic",
      "Punk",
      "Industrial",
      "Dystopian",
      "Utopian",
      "Mythic",
      "Legendary",
      "Lost",
      "Forgotten",
      "Reborn",
      "Decadent",
      "Emerging",
      "Relentless",
      "Unbreakable",
      "Invisible",
      "Ineffable",
    ],
    nouns: [
      "Thunder",
      "Wolf",
      "King",
      "Abyss",
      "Secret",
      "Edge",
      "Echo",
      "Volcano",
      "Ocean",
      "Heart",
      "Ghost",
      "Temple",
      "Dragon",
      "Phoenix",
      "Colossus",
      "Titan",
      "Giant",
      "Angel",
      "Demon",
      "Prophet",
      "Shaman",
      "Necromancer",
      "Alchemist",
      "Wanderer",
      "Nomad",
      "Pilgrim",
      "Knight",
      "Samurai",
      "Viking",
      "Gladiator",
      "Wizard",
      "Warlock",
      "Sorcerer",
      "Oracle",
      "Sage",
      "Enlightened",
      "Martyr",
      "Hero",
      "Villain",
      "Mercenary",
      "Corsair",
      "Pirate",
      "Astrologer",
      "Astronomer",
      "Cosmonaut",
      "Traveler",
      "Explorer",
      "Pioneer",
      "Trailblazer",
      "Mist",
      "Storm",
      "Hurricane",
      "Tsunami",
      "Earthquake",
      "Avalanche",
      "Eruption",
      "Cyclone",
      "Tornado",
      "Gale",
      "Monolith",
      "Obelisk",
      "Pyramid",
      "Ziggurat",
      "Citadel",
      "Fortress",
      "Bastille",
      "Castle",
      "Palace",
      "Mansion",
      "Cathedral",
      "Monastery",
      "Shrine",
      "Sanctuary",
      "Altar",
      "Pantheon",
      "Olympus",
      "Valhalla",
      "Nirvana",
      "Eden",
      "Hell",
      "Purgatory",
      "Limbo",
      "Void",
      "Vacuum",
      "Vortex",
      "Singularity",
      "Black Hole",
      "Galaxy",
      "Constellation",
      "Nebula",
      "Supernova",
      "Comet",
      "Asteroid",
      "Meteor",
      "Planet",
      "Satellite",
      "Moon",
      "Sun",
      "Star",
      "Eclipse",
      "Aurora",
      "Twilight",
      "Dawn",
      "Dusk",
      "Midnight",
      "Daybreak",
    ],
    verbs: [
      "Roaring",
      "Screaming",
      "Whispering",
      "Singing",
      "Dancing",
      "Flying",
      "Falling",
      "Ascending",
      "Descending",
      "Burning",
      "Freezing",
      "Dissolving",
      "Creating",
      "Destroying",
      "Transforming",
      "Evolving",
      "Devouring",
      "Consuming",
      "Purifying",
      "Corrupting",
      "Illuminating",
      "Darkening",
      "Healing",
      "Poisoning",
      "Cursing",
      "Blessing",
      "Prophesying",
      "Divining",
      "Remembering",
      "Forgetting",
      "Dreaming",
      "Waking",
      "Sleeping",
      "Living",
      "Dying",
      "Reborning",
      "Perishing",
    ],
    places: [
      "Graveyard",
      "Desert",
      "Forest",
      "Mountain",
      "Cave",
      "Grotto",
      "Abyss",
      "Cliff",
      "Island",
      "Continent",
      "Plain",
      "Valley",
      "Canyon",
      "Ravine",
      "Gorge",
      "Strait",
      "Ocean",
      "River",
      "Lake",
      "Lagoon",
      "Waterfall",
      "Glacier",
      "Volcano",
      "Crater",
      "Metropolis",
      "City",
      "Town",
      "Village",
      "Slum",
      "Suburb",
      "Downtown",
      "Outskirts",
      "Station",
      "Port",
      "Airport",
      "Terminal",
      "Garage",
      "Warehouse",
      "Depot",
      "Laboratory",
      "Observatory",
      "Library",
      "Archive",
      "Museum",
      "Gallery",
      "Theater",
      "Cinema",
      "Arena",
      "Coliseum",
      "Stadium",
      "Gym",
      "Academy",
      "Sanctuary",
      "Altar",
      "Tabernacle",
      "Monastery",
      "Convent",
      "Hermitage",
      "Chapel",
      "Church",
      "Cathedral",
      "Mosque",
      "Synagogue",
      "Temple",
      "Pagoda",
      "Ziggurat",
      "Pyramid",
      "Tower",
      "Lighthouse",
      "Bunker",
      "Silo",
      "Mine",
      "Tunnel",
      "Catacomb",
      "Crypt",
      "Mausoleum",
      "Sepulcher",
      "Ship",
      "Rocket",
      "Space Shuttle",
      "Space Station",
      "Planet",
      "Moon",
      "Asteroid",
      "Comet",
      "Nebula",
      "Galaxy",
      "Universe",
      "Multiverse",
      "Reality",
      "Dimension",
    ],
    concepts: [
      "Freedom",
      "Destiny",
      "Luck",
      "Misfortune",
      "Love",
      "Hate",
      "Peace",
      "War",
      "Chaos",
      "Order",
      "Time",
      "Space",
      "Matter",
      "Energy",
      "Consciousness",
      "Unconsciousness",
      "Memory",
      "Forgetfulness",
      "Truth",
      "Lie",
      "Reality",
      "Illusion",
      "Dream",
      "Nightmare",
      "Life",
      "Death",
      "Resurrection",
      "Reincarnation",
      "Transcendence",
      "Enlightenment",
      "Salvation",
      "Condemnation",
      "Paradise",
      "Hell",
      "Purgatory",
      "Nirvana",
      "Ecstasy",
      "Agony",
      "Pleasure",
      "Pain",
      "Joy",
      "Sadness",
      "Anger",
      "Calm",
      "Madness",
      "Sanity",
      "Genius",
      "Insanity",
      "Beauty",
      "Horror",
      "Sublime",
      "Terrible",
      "Divine",
      "Profane",
      "Sacred",
      "Cursed",
      "Blessed",
      "Pure",
      "Impure",
      "Innocent",
      "Guilty",
      "Revenge",
      "Forgiveness",
      "Redemption",
      "Fall",
      "Ascension",
    ],
    articles: ["The", "A", "An", "Some"],
    connectors: [
      "of",
      "from",
      "in",
      "and",
      "or",
      "with",
      "without",
      "beyond",
      "within",
    ],
    prefixes: [
      "Anti",
      "Arch",
      "Auto",
      "Bi",
      "Co",
      "Counter",
      "De",
      "Ex",
      "Hyper",
      "Infra",
      "Inter",
      "Intra",
      "Macro",
      "Micro",
      "Mono",
      "Multi",
      "Neo",
      "Pan",
      "Post",
      "Pre",
      "Pro",
      "Re",
      "Retro",
      "Semi",
      "Over",
      "Sub",
      "Super",
      "Supra",
      "Tele",
      "Trans",
      "Tri",
      "Ultra",
      "Vice",
      "Cyber",
      "Techno",
      "Neuro",
      "Bio",
      "Eco",
      "Geo",
      "Aero",
      "Hydro",
      "Pyro",
      "Crypto",
      "Digi",
      "Meta",
      "Nano",
      "Omni",
      "Paleo",
      "Proto",
      "Psyche",
      "Quantum",
      "Radio",
      "Thermo",
      "Xeno",
    ],
  },
  es: {
    adjectives: [
      "Solitario",
      "Eterno",
      "Veloz",
      "Sagrado",
      "Oscuro",
      "Lunar",
      "Eléctrico",
      "Caótico",
      "Silencioso",
      "Feroz",
      "Dorado",
      "Ultra",
      "Cósmico",
      "Nuclear",
      "Psicodélico",
      "Sombrío",
      "Radioactivo",
      "Cristalino",
      "Arcano",
      "Mecánico",
      "Digital",
      "Primitivo",
      "Celestial",
      "Subterráneo",
      "Desértico",
      "Oceánico",
      "Forestal",
      "Metálico",
      "Volcánico",
      "Glacial",
      "Cuántico",
      "Atómico",
      "Místico",
      "Helado",
      "Incandescente",
      "Nocturno",
      "Diurno",
      "Etéreo",
      "Ancestral",
      "Futurista",
      "Retro",
      "Neón",
      "Gótico",
      "Punk",
      "Industrial",
      "Distópico",
      "Utópico",
      "Mítico",
      "Legendario",
      "Perdido",
      "Olvidado",
      "Renacido",
      "Decadente",
      "Emergente",
      "Implacable",
      "Irrompible",
      "Invisible",
      "Inefable",
    ],
    nouns: [
      "Trueno",
      "Lobo",
      "Rey",
      "Abismo",
      "Secreto",
      "Vértice",
      "Eco",
      "Volcán",
      "Mar",
      "Corazón",
      "Fantasma",
      "Templo",
      "Dragón",
      "Fénix",
      "Coloso",
      "Titán",
      "Gigante",
      "Ángel",
      "Demonio",
      "Profeta",
      "Chamán",
      "Nigromante",
      "Alquimista",
      "Caminante",
      "Nómada",
      "Peregrino",
      "Caballero",
      "Samurái",
      "Vikingo",
      "Gladiador",
      "Mago",
      "Brujo",
      "Hechicero",
      "Oráculo",
      "Sabio",
      "Iluminado",
      "Mártir",
      "Héroe",
      "Villano",
      "Mercenario",
      "Corsario",
      "Pirata",
      "Astrólogo",
      "Astrónomo",
      "Cosmonauta",
      "Viajero",
      "Explorador",
      "Pionero",
      "Desbravador",
      "Neblina",
      "Tempestad",
      "Huracán",
      "Tsunami",
      "Terremoto",
      "Avalancha",
      "Erupción",
      "Ciclón",
      "Tornado",
      "Vendaval",
      "Monolito",
      "Obelisco",
      "Pirámide",
      "Zigurat",
      "Ciudadela",
      "Fortaleza",
      "Bastilla",
      "Castillo",
      "Palacio",
      "Mansión",
      "Catedral",
      "Monasterio",
      "Santuario",
      "Sagrario",
      "Altar",
      "Panteón",
      "Olimpo",
      "Valhalla",
      "Nirvana",
      "Edén",
      "Infierno",
      "Purgatorio",
      "Limbo",
      "Vacío",
      "Vórtice",
      "Singularidad",
      "Agujero Negro",
      "Galaxia",
      "Constelación",
      "Nebulosa",
      "Supernova",
      "Cometa",
      "Asteroide",
      "Meteoro",
      "Planeta",
      "Satélite",
      "Luna",
      "Sol",
      "Estrella",
      "Eclipse",
      "Aurora",
      "Crepúsculo",
      "Alba",
      "Ocaso",
      "Medianoche",
      "Madrugada",
    ],
    verbs: [
      "Rugiendo",
      "Gritando",
      "Susurrando",
      "Cantando",
      "Bailando",
      "Volando",
      "Cayendo",
      "Ascendiendo",
      "Descendiendo",
      "Quemando",
      "Congelando",
      "Disolviendo",
      "Creando",
      "Destruyendo",
      "Transformando",
      "Evolucionando",
      "Devorando",
      "Consumiendo",
      "Purificando",
      "Corrompiendo",
      "Iluminando",
      "Oscureciendo",
      "Sanando",
      "Envenenando",
      "Maldiciendo",
      "Bendiciendo",
      "Profetizando",
      "Adivinando",
      "Recordando",
      "Olvidando",
      "Soñando",
      "Despertando",
      "Durmiendo",
      "Viviendo",
      "Muriendo",
      "Renaciendo",
      "Pereciendo",
    ],
    places: [
      "Cementerio",
      "Desierto",
      "Bosque",
      "Montaña",
      "Caverna",
      "Gruta",
      "Abismo",
      "Acantilado",
      "Isla",
      "Continente",
      "Llanura",
      "Valle",
      "Cañón",
      "Barranco",
      "Garganta",
      "Estrecho",
      "Océano",
      "Río",
      "Lago",
      "Laguna",
      "Cascada",
      "Glaciar",
      "Volcán",
      "Cráter",
      "Metrópolis",
      "Ciudad",
      "Pueblo",
      "Aldea",
      "Barrio",
      "Suburbio",
      "Centro",
      "Periferia",
      "Estación",
      "Puerto",
      "Aeropuerto",
      "Terminal",
      "Garaje",
      "Almacén",
      "Depósito",
      "Laboratorio",
      "Observatorio",
      "Biblioteca",
      "Archivo",
      "Museo",
      "Galería",
      "Teatro",
      "Cine",
      "Arena",
      "Coliseo",
      "Estadio",
      "Gimnasio",
      "Academia",
      "Santuario",
      "Altar",
      "Tabernáculo",
      "Monasterio",
      "Convento",
      "Ermita",
      "Capilla",
      "Iglesia",
      "Catedral",
      "Mezquita",
      "Sinagoga",
      "Templo",
      "Pagoda",
      "Zigurat",
      "Pirámide",
      "Torre",
      "Faro",
      "Búnker",
      "Silo",
      "Mina",
      "Túnel",
      "Catacumba",
      "Cripta",
      "Mausoleo",
      "Sepulcro",
      "Nave",
      "Cohete",
      "Transbordador",
      "Estación Espacial",
      "Planeta",
      "Luna",
      "Asteroide",
      "Cometa",
      "Nebulosa",
      "Galaxia",
      "Universo",
      "Multiverso",
      "Realidad",
      "Dimensión",
    ],
    concepts: [
      "Libertad",
      "Destino",
      "Suerte",
      "Mala Suerte",
      "Amor",
      "Odio",
      "Paz",
      "Guerra",
      "Caos",
      "Orden",
      "Tiempo",
      "Espacio",
      "Materia",
      "Energía",
      "Conciencia",
      "Inconsciencia",
      "Memoria",
      "Olvido",
      "Verdad",
      "Mentira",
      "Realidad",
      "Ilusión",
      "Sueño",
      "Pesadilla",
      "Vida",
      "Muerte",
      "Resurrección",
      "Reencarnación",
      "Trascendencia",
      "Iluminación",
      "Salvación",
      "Condenación",
      "Paraíso",
      "Infierno",
      "Purgatorio",
      "Nirvana",
      "Éxtasis",
      "Agonía",
      "Placer",
      "Dolor",
      "Alegría",
      "Tristeza",
      "Ira",
      "Calma",
      "Locura",
      "Cordura",
      "Genio",
      "Insania",
      "Belleza",
      "Horror",
      "Sublime",
      "Terrible",
      "Divino",
      "Profano",
      "Sagrado",
      "Maldito",
      "Bendito",
      "Puro",
      "Impuro",
      "Inocente",
      "Culpable",
      "Venganza",
      "Perdón",
      "Redención",
      "Caída",
      "Ascensión",
    ],
    articles: ["Los", "Las", "El", "La", "Un", "Una", "Unos", "Unas"],
    connectors: [
      "del",
      "de",
      "de la",
      "y",
      "o",
      "con",
      "sin",
      "más allá",
      "dentro de",
    ],
    prefixes: [
      "Anti",
      "Arqui",
      "Auto",
      "Bi",
      "Co",
      "Contra",
      "Des",
      "Ex",
      "Hiper",
      "Infra",
      "Inter",
      "Intra",
      "Macro",
      "Micro",
      "Mono",
      "Multi",
      "Neo",
      "Pan",
      "Post",
      "Pre",
      "Pro",
      "Re",
      "Retro",
      "Semi",
      "Sobre",
      "Sub",
      "Super",
      "Supra",
      "Tele",
      "Trans",
      "Tri",
      "Ultra",
      "Vice",
      "Cyber",
      "Techno",
      "Neuro",
      "Bio",
      "Eco",
      "Geo",
      "Aero",
      "Hidro",
      "Piro",
      "Crypto",
      "Digi",
      "Meta",
      "Nano",
      "Omni",
      "Paleo",
      "Proto",
      "Psico",
      "Quantum",
      "Radio",
      "Termo",
      "Xeno",
    ],
  },
};

const GENRE_WORDS: Record<NameGenre, Record<NameLanguage, string[]>> = {
  rock: {
    pt: [
      "Pedra",
      "Guitarra",
      "Amplificador",
      "Riff",
      "Power",
      "Hard",
      "Heavy",
      "Metal",
    ],
    en: [
      "Stone",
      "Guitar",
      "Amplifier",
      "Riff",
      "Power",
      "Hard",
      "Heavy",
      "Metal",
    ],
    es: [
      "Piedra",
      "Guitarra",
      "Amplificador",
      "Riff",
      "Power",
      "Hard",
      "Heavy",
      "Metal",
    ],
  },
  metal: {
    pt: [
      "Aço",
      "Espada",
      "Martelo",
      "Forja",
      "Caveira",
      "Cruz",
      "Sangue",
      "Trovão",
    ],
    en: [
      "Steel",
      "Sword",
      "Hammer",
      "Forge",
      "Skull",
      "Cross",
      "Blood",
      "Thunder",
    ],
    es: [
      "Acero",
      "Espada",
      "Martillo",
      "Forja",
      "Calavera",
      "Cruz",
      "Sangre",
      "Trueno",
    ],
  },
  electronic: {
    pt: [
      "Sintetizador",
      "Batida",
      "Loop",
      "Sample",
      "Digital",
      "Byte",
      "Chip",
      "Glitch",
    ],
    en: [
      "Synthesizer",
      "Beat",
      "Loop",
      "Sample",
      "Digital",
      "Byte",
      "Chip",
      "Glitch",
    ],
    es: [
      "Sintetizador",
      "Ritmo",
      "Loop",
      "Sample",
      "Digital",
      "Byte",
      "Chip",
      "Glitch",
    ],
  },
  punk: {
    pt: [
      "Rebelde",
      "Anarquia",
      "Corrente",
      "Rasgado",
      "Spike",
      "Protesto",
      "Caos",
    ],
    en: ["Rebel", "Anarchy", "Chain", "Torn", "Spike", "Protest", "Chaos"],
    es: [
      "Rebelde",
      "Anarquía",
      "Cadena",
      "Rasgado",
      "Spike",
      "Protesta",
      "Caos",
    ],
  },
};

const COLORS: Record<NameLanguage, string[]> = {
  pt: [
    "Negro",
    "Branco",
    "Vermelho",
    "Azul",
    "Verde",
    "Amarelo",
    "Roxo",
    "Cinza",
  ],
  en: ["Black", "White", "Red", "Blue", "Green", "Yellow", "Purple", "Gray"],
  es: [
    "Negro",
    "Blanco",
    "Rojo",
    "Azul",
    "Verde",
    "Amarillo",
    "Púrpura",
    "Gris",
  ],
};

/** Picks a random element from a non-empty array. */
function pick<T>(array: readonly T[]): T {
  return array[Math.floor(Math.random() * array.length)];
}

type Pattern = (
  lang: NameLanguage,
  includeArticle: boolean,
  genre?: NameGenre,
) => string;

const PATTERNS: Pattern[] = [
  // Article + Adjective + Noun
  (lang, includeArticle) => {
    const w = WORDS[lang];
    const article = includeArticle ? `${pick(w.articles)} ` : "";
    return `${article}${pick(w.adjectives)} ${pick(w.nouns)}`;
  },
  // Article + Noun + Connector + Noun
  (lang, includeArticle) => {
    const w = WORDS[lang];
    const article = includeArticle ? `${pick(w.articles)} ` : "";
    return `${article}${pick(w.nouns)} ${pick(w.connectors)} ${pick(w.nouns)}`;
  },
  // Verb + Noun
  (lang) => {
    const w = WORDS[lang];
    return `${pick(w.verbs)} ${pick(w.nouns)}`;
  },
  // Concept + Connector + Place
  (lang) => {
    const w = WORDS[lang];
    const connector = lang === "en" ? "of" : lang === "es" ? "de" : "do";
    return `${pick(w.concepts)} ${connector} ${pick(w.places)}`;
  },
  // Prefix + Noun
  (lang) => {
    const w = WORDS[lang];
    return `${pick(w.prefixes)}${pick(w.nouns)}`;
  },
  // Color + Noun
  (lang) => {
    const w = WORDS[lang];
    return `${pick(COLORS[lang])} ${pick(w.nouns)}`;
  },
  // Genre-specific word + Noun/Adjective (falls back to pattern 0)
  (lang, includeArticle, genre) => {
    if (!genre || !GENRE_WORDS[genre]) {
      return PATTERNS[0](lang, includeArticle, genre);
    }
    const w = WORDS[lang];
    const first = pick(GENRE_WORDS[genre][lang]);
    const second = pick([...w.nouns, ...w.adjectives]);
    return `${first} ${second}`;
  },
];

/**
 * Generates a single band name using a randomly chosen pattern.
 *
 * @param options - Language, article and genre options.
 * @returns A generated band name.
 */
export function generateBandName(options: GenerateNameOptions = {}): string {
  const language = options.language ?? "pt";
  const includeArticle = options.includeArticle ?? true;
  return pick(PATTERNS)(language, includeArticle, options.genre);
}

/**
 * Generates up to `count` unique band names.
 *
 * @param count - Desired number of names.
 * @param options - Language, article and genre options.
 * @returns The generated (deduplicated) names.
 */
export function generateBandNames(
  count: number,
  options: GenerateNameOptions = {},
): string[] {
  const names = new Set<string>();
  let guard = 0;
  const maxGuard = count * 20;
  while (names.size < count && names.size < 100 && guard < maxGuard) {
    names.add(generateBandName(options));
    guard += 1;
  }
  return [...names];
}
