/**
 * Band name generator — pure functions ported (and simplified to pt-BR) from
 * the `game-music` frontend `BandNameGenerator`. No side effects beyond
 * `Math.random()`; safe to call from a use case.
 */

const ADJECTIVES = [
  "Solitário",
  "Eterno",
  "Veloz",
  "Sagrado",
  "Escuro",
  "Lunar",
  "Elétrico",
  "Caótico",
  "Silencioso",
  "Feroz",
  "Dourado",
  "Cósmico",
  "Nuclear",
  "Psicodélico",
  "Sombrio",
  "Radioativo",
  "Cristalino",
  "Arcano",
  "Mecânico",
  "Digital",
  "Primitivo",
  "Celestial",
  "Subterrâneo",
  "Metálico",
  "Vulcânico",
  "Glacial",
  "Quântico",
  "Atômico",
  "Místico",
  "Noturno",
  "Etéreo",
  "Ancestral",
  "Futurista",
  "Neon",
  "Gótico",
  "Distópico",
  "Mítico",
  "Lendário",
  "Perdido",
  "Esquecido",
  "Renascido",
  "Decadente",
  "Implacável",
  "Inquebrável",
  "Invisível",
] as const;

const NOUNS = [
  "Trovão",
  "Lobo",
  "Rei",
  "Abismo",
  "Segredo",
  "Vértice",
  "Eco",
  "Vulcão",
  "Oceano",
  "Coração",
  "Fantasma",
  "Templo",
  "Dragão",
  "Fênix",
  "Colosso",
  "Titã",
  "Anjo",
  "Demônio",
  "Profeta",
  "Xamã",
  "Alquimista",
  "Andarilho",
  "Nômade",
  "Cavaleiro",
  "Samurai",
  "Viking",
  "Gladiador",
  "Mago",
  "Oráculo",
  "Herói",
  "Mercenário",
  "Pirata",
  "Névoa",
  "Tempestade",
  "Furacão",
  "Tsunami",
  "Ciclone",
  "Tornado",
  "Monólito",
  "Obelisco",
  "Fortaleza",
  "Castelo",
  "Catedral",
  "Santuário",
  "Panteão",
  "Valhalla",
  "Nirvana",
  "Vórtice",
  "Galáxia",
  "Nebulosa",
  "Supernova",
  "Cometa",
  "Meteoro",
  "Estrela",
  "Eclipse",
  "Aurora",
  "Crepúsculo",
  "Madrugada",
] as const;

const VERBS = [
  "Rugindo",
  "Gritando",
  "Sussurrando",
  "Cantando",
  "Dançando",
  "Voando",
  "Caindo",
  "Ascendendo",
  "Queimando",
  "Congelando",
  "Criando",
  "Destruindo",
  "Transformando",
  "Evoluindo",
  "Devorando",
  "Purificando",
  "Iluminando",
  "Sonhando",
  "Renascendo",
] as const;

const PLACES = [
  "Cemitério",
  "Deserto",
  "Floresta",
  "Montanha",
  "Caverna",
  "Abismo",
  "Penhasco",
  "Ilha",
  "Vale",
  "Cânion",
  "Oceano",
  "Cachoeira",
  "Geleira",
  "Vulcão",
  "Cratera",
  "Metrópole",
  "Cidade",
  "Estação",
  "Porto",
  "Observatório",
  "Biblioteca",
  "Museu",
  "Arena",
  "Coliseu",
  "Templo",
  "Catedral",
  "Torre",
  "Farol",
  "Bunker",
  "Mina",
  "Túnel",
  "Cripta",
  "Nave",
  "Nebulosa",
  "Galáxia",
  "Dimensão",
] as const;

const CONCEPTS = [
  "Liberdade",
  "Destino",
  "Sorte",
  "Amor",
  "Ódio",
  "Paz",
  "Guerra",
  "Caos",
  "Ordem",
  "Tempo",
  "Espaço",
  "Energia",
  "Memória",
  "Verdade",
  "Ilusão",
  "Sonho",
  "Pesadelo",
  "Vida",
  "Morte",
  "Transcendência",
  "Iluminação",
  "Êxtase",
  "Loucura",
  "Beleza",
  "Horror",
  "Vingança",
  "Redenção",
  "Queda",
  "Ascensão",
] as const;

const ARTICLES = ["Os", "As", "O", "A"] as const;

const CONNECTORS = ["do", "da", "de", "dos", "das", "no", "na"] as const;

const PREFIXES = [
  "Anti",
  "Auto",
  "Contra",
  "Hiper",
  "Inter",
  "Macro",
  "Micro",
  "Multi",
  "Neo",
  "Pós",
  "Pré",
  "Retro",
  "Sub",
  "Super",
  "Trans",
  "Ultra",
  "Cyber",
  "Tecno",
  "Neuro",
  "Bio",
  "Eco",
  "Cripto",
  "Meta",
  "Nano",
  "Omni",
  "Proto",
  "Psico",
] as const;

const COLORS = [
  "Negro",
  "Branco",
  "Vermelho",
  "Azul",
  "Verde",
  "Amarelo",
  "Roxo",
  "Cinza",
] as const;

/**
 * Picks a random element from a non-empty array.
 *
 * @param array - The array to pick from.
 * @returns A random element.
 */
function pick<T>(array: readonly T[]): T {
  return array[Math.floor(Math.random() * array.length)];
}

/** The name-shape patterns, each producing a full band name. */
const PATTERNS: ReadonlyArray<() => string> = [
  () => `${pick(ARTICLES)} ${pick(ADJECTIVES)} ${pick(NOUNS)}`,
  () => `${pick(ARTICLES)} ${pick(NOUNS)} ${pick(CONNECTORS)} ${pick(NOUNS)}`,
  () => `${pick(VERBS)} ${pick(NOUNS)}`,
  () => `${pick(CONCEPTS)} do ${pick(PLACES)}`,
  () => `${pick(PREFIXES)}${pick(NOUNS)}`,
  () => `${pick(COLORS)} ${pick(NOUNS)}`,
];

/**
 * Generates a single random band name using a randomly chosen pattern.
 *
 * @returns A generated band name.
 */
export function generateBandName(): string {
  return pick(PATTERNS)();
}
